from .settings_panel_view import SettingsPanelView
from .waypoints_logger_panel_view import WaypointsLoggerPanelView
from .waypoints_navigator_panel_view import WaypointsNavigatorPanelView

from .nav_settings_panel_view import NavSettingsPanelView
from .ntrip_settings_panel_view import NTRIPSettingsPanelView
from .other_settings_panel_view import OtherSettingsPanelView