


# foxglove
foxglove_ws_uri: ws://localhost:8765
foxglove_ws_subprotocol: foxglove.websocket.v1

# map api key
bing_api_key: "AkCDUXwYzM3w36XYcNeT0kNOFhpTiQuwluXkQlFBs1WhFbknP2_2iDBXeL_WzXCc"
google_maps_api_key: "AIzaSyB6wDcBKTq5ORK6TEOD-dDxdTPWkZs6ZlI"

# container
container_image: "ghcr.io/serene4mr/mowbot_legacy:latest"
container_stop_timeout: 1

# others
mowbot_legacy_data_path: "/mowbot_legacy_data"
waypoints_file: "__waypoints__.yaml"
nav_params_file: "__nav_params__.yaml"
ntrip_params_file: "__ntrip_params__.yaml"
cmdvel_scaler_params_file: "__cmdvel_scaler_params__.yaml"
kt_server_bridge_params_file: "__kt_server_bridge_params__.yaml"